const IMG={
  quarry:'https://images.pexels.com/photos/36224103/pexels-photo-36224103.jpeg?auto=compress&cs=tinysrgb&w=1200',
  openpit:'https://images.pexels.com/photos/38643910/pexels-photo-38643910.jpeg?auto=compress&cs=tinysrgb&w=1200',
  truck:'https://images.pexels.com/photos/5125104/pexels-photo-5125104.jpeg?auto=compress&cs=tinysrgb&w=1200',
  truckSA:'https://images.pexels.com/photos/27533504/pexels-photo-27533504.jpeg?auto=compress&cs=tinysrgb&w=1200',
  aerialMine:'https://images.pexels.com/photos/31498922/pexels-photo-31498922.jpeg?auto=compress&cs=tinysrgb&w=1200',
  mountain:'https://images.pexels.com/photos/33337903/pexels-photo-33337903.jpeg?auto=compress&cs=tinysrgb&w=1200',
  greenMtn:'https://images.pexels.com/photos/20043916/pexels-photo-20043916.png?auto=compress&cs=tinysrgb&w=1200',
  aerialMtn:'https://images.pexels.com/photos/17577893/pexels-photo-17577893.jpeg?auto=compress&cs=tinysrgb&w=1200',
  sunset:'https://images.pexels.com/photos/8798119/pexels-photo-8798119.jpeg?auto=compress&cs=tinysrgb&w=1200',
  excavator:'https://images.pexels.com/photos/15071423/pexels-photo-15071423.jpeg?auto=compress&cs=tinysrgb&w=1200',
  stoneQuarry:'https://images.pexels.com/photos/15138925/pexels-photo-15138925.jpeg?auto=compress&cs=tinysrgb&w=1200',
  goldBars:'https://images.pexels.com/photos/8442325/pexels-photo-8442325.jpeg?auto=compress&cs=tinysrgb&w=1200',
  goldRed:'https://images.pexels.com/photos/342950/pexels-photo-342950.jpeg?auto=compress&cs=tinysrgb&w=1200',
  workers:'https://images.pexels.com/photos/38706752/pexels-photo-38706752.jpeg?auto=compress&cs=tinysrgb&w=1200',
  teamSA:'https://images.pexels.com/photos/5298215/pexels-photo-5298215.jpeg?auto=compress&cs=tinysrgb&w=1200',
  meeting:'https://images.pexels.com/photos/7433847/pexels-photo-7433847.jpeg?auto=compress&cs=tinysrgb&w=1200',
  meeting2:'https://images.pexels.com/photos/7433853/pexels-photo-7433853.jpeg?auto=compress&cs=tinysrgb&w=1200',
  farming:'https://images.pexels.com/photos/10988625/pexels-photo-10988625.jpeg?auto=compress&cs=tinysrgb&w=1200',
  community:'https://images.pexels.com/photos/31763371/pexels-photo-31763371.jpeg?auto=compress&cs=tinysrgb&w=1200',
  forest:'https://images.pexels.com/photos/3923727/pexels-photo-3923727.jpeg?auto=compress&cs=tinysrgb&w=1200',
  handshake:'https://images.pexels.com/photos/4483559/pexels-photo-4483559.jpeg?auto=compress&cs=tinysrgb&w=1200',
  bucketWheel:'https://images.pexels.com/photos/4993793/pexels-photo-4993793.jpeg?auto=compress&cs=tinysrgb&w=1200',
  sandDunes:'https://images.pexels.com/photos/29389505/pexels-photo-29389505.jpeg?auto=compress&cs=tinysrgb&w=1200',
  conveyor:'https://images.pexels.com/photos/14484386/pexels-photo-14484386.jpeg?auto=compress&cs=tinysrgb&w=1200',
};
const c=(title,text)=>`<article class="card anim-up"><span class="card-mark"></span><h3>${title}</h3><p>${text}</p></article>`;
const imgCard=(title,text,src,alt)=>`<article class="card img-card anim-up"><div class="card-img"><img src="${src}" alt="${alt}" loading="lazy"></div><span class="card-mark"></span><h3>${title}</h3><p>${text}</p></article>`;
const hero=(k,t,d,a='Explore our work',href='/mining/projects/lunga',img=null)=>`<section class="hero inner${img?' hero-photo':''}"><div class="anim-up"><span class="eyebrow">${k}</span><h1>${t}</h1><p>${d}</p><a class="button" href="${href}">${a} <span>↗</span></a></div>${img?`<div class="hero-image"><img src="${img}" alt="${t}" loading="eager"></div>`:`<div class="terrain" role="img" aria-label="Abstract topographic illustration"><i></i><b>08°<br><small>EAST AFRICA</small></b></div>`}</section>`;
const photoBreak=(src,alt,caption)=>`<section class="photo-break"><img src="${src}" alt="${alt}" loading="lazy"><div class="photo-caption"><span>${caption}</span></div></section>`;
const form=(type)=>`<form name="${type}" method="post" data-netlify="true"><input type="hidden" name="form-name" value="${type}"><div class="field"><label for="${type}-name">Full name</label><input id="${type}-name" name="name" autocomplete="name" required></div><div class="field"><label for="${type}-email">Work email</label><input id="${type}-email" name="email" type="email" autocomplete="email" required></div><div class="field full"><label for="${type}-org">Organisation</label><input id="${type}-org" name="organisation" autocomplete="organization"></div><div class="field full"><label for="${type}-message">How can we help?</label><textarea id="${type}-message" name="message" rows="5" required></textarea></div><label class="consent"><input type="checkbox" name="consent" required> I agree that Perpach may use this information to respond, as described in the <a href="/mining/privacy">privacy notice</a>.</label><button class="button" type="submit">Send inquiry <span>↗</span></button><p class="form-note">Please do not submit identity documents, banking details, confidential technical data, or investment funds.</p></form>`;
export const pages=[
{slug:'',title:'Mining with local knowledge and long-term discipline',description:'Perpach is an Ethiopian-founded mining operator and project developer.',body:`<section class="hero home"><div class="anim-up"><span class="eyebrow">PERPACH METALS &amp; MINING</span><h1>Mining with<br><em>local knowledge.</em></h1><p>An Ethiopian-founded mining business building responsible operations through evidence, professional management and long-term partnership.</p><div class="actions"><a class="button" href="/mining/company">Our company <span>↗</span></a><a class="text-link" href="/mining/projects/lunga">View Lunga Project →</a></div></div><div class="terrain hero-art"><i></i><b>LUNGA<br><small>ETHIOPIA</small></b></div><div class="scroll">SCROLL TO DISCOVER ↓</div></section>

<section class="statement anim-up"><span class="eyebrow">WHO WE ARE</span><h2>Established on the ground.<br><em>Preparing for what comes next.</em></h2><div><p>Perpach is an Ethiopian-founded mining business focused on early operations and project development. Our ambition is simple: build a professionally managed mining platform grounded in local experience.</p><p>We work where many talk. Several years of site-level experience have taught us what it takes to build a responsible mining operation from scratch in East Africa — and what remains ahead.</p><a class="text-link" href="/mining/company">Discover our company →</a></div></section>

${photoBreak(IMG.aerialMine,'Aerial view of active mining operations','FIELD OPERATIONS / EAST AFRICA')}

<section class="snapshot"><div class="photo-panel" style="background-image:url(${IMG.excavator})"><span>FIELD NOTES / LUNGA</span></div><div><span class="eyebrow">FLAGSHIP WORK</span><h2>The Lunga Project</h2><p>Lunga is an early operation moving into a new phase of verification, stronger controls and professional management. What exists today is a practical foundation — not a finished mine.</p><p>The next phase centres on independent review, controlled production data and clear operating responsibilities before any expansion commitments are made.</p><dl><div><dt>LOCATION</dt><dd>Ethiopia</dd></div><div><dt>COMMODITY</dt><dd>Gold</dd></div><div><dt>STAGE</dt><dd>Early operation</dd></div><div><dt>TARGET</dt><dd>Verification &amp; stabilisation</dd></div></dl><a class="button light" href="/mining/projects/lunga">Explore Lunga <span>↗</span></a></div></section>

<section class="section"><div class="section-head anim-up"><span class="eyebrow">HOW WE WORK</span><h2>A more disciplined path to growth.</h2><p>We publish what can be supported, distinguish current practice from future intent, and invite the right expertise into the work.</p></div><div class="cards">${c('Local knowledge','Operating insight shaped by time on the ground and relationships built locally. We understand the terrain, the people and the regulatory reality.')}${c('Evidence-led growth','Verification, reconciliation and controlled decision-making before expansion. Every claim is backed by data we can defend.')}${c('Professional partnership','Experienced operators, technical specialists and aligned strategic capital working within a clear governance framework.')}${c('Responsible operations','Improving safety, environmental and community practices as the business develops. We report what is implemented, not what is aspirational.')}</div></section>

<section class="numbers"><div class="numbers-grid">${[['Ethiopia','Home base &amp; operations'],['Gold','Primary commodity focus'],['4-Stage','Development pathway'],['2026','Professionalisation year']].map(([v,l])=>`<div class="num-item anim-up"><b>${v}</b><span>${l}</span></div>`).join('')}</div></section>

${photoBreak(IMG.mountain,'Ethiopian mountain landscape at sunset','THE LANDSCAPE / WHERE WE OPERATE')}

<section class="updates"><span class="eyebrow">LATEST UPDATES</span><div class="update-head"><h2>From the field</h2><a class="text-link" href="/mining/newsroom">View newsroom →</a></div><div class="news-grid">${imgCard('A stronger operating baseline','12 AUG 2026 · OPERATIONS — Production controls and reconciliation are central to Lunga\'s next phase. New measurement protocols are being implemented across all active zones.',IMG.openpit,'Mining operations')}${imgCard('Building the right partnerships','04 AUG 2026 · COMPANY — Perpach outlines the capabilities sought for its professionalisation programme, including mine planning, geological interpretation and financial controls.',IMG.meeting,'Business partnership meeting')}${imgCard('Responsibility in practice','22 JUL 2026 · RESPONSIBILITY — How implementation status shapes our public commitments. A candid look at what is working and what needs investment.',IMG.forest,'Environmental conservation')}</div></section>

<section class="pathways"><span class="eyebrow">WORK WITH PERPACH</span><h2>Different expertise.<br>One shared standard.</h2><div><a href="/mining/careers">Build your career <span>↗</span></a><a href="/mining/partnerships">Supply and partner <span>↗</span></a><a href="/mining/investor">Strategic investment <span>↗</span></a><a href="/mining/contact">General contact <span>↗</span></a></div></section>`},

{slug:'company',title:'Company',description:'Learn about the purpose, history and operating principles behind Perpach Metals and Mining.',body:`${hero('OUR COMPANY','Built from the ground up.','A mining business shaped by practical site experience and a clear-eyed understanding of what responsible growth requires.',
'Explore Lunga','/mining/projects/lunga',IMG.sunset)}

<section class="section"><div class="section-head anim-up"><span class="eyebrow">OUR PURPOSE</span><h2>Clarity before scale.</h2><p>We build durable mining operations that create value through local capability and professional discipline. Everything else follows from that.</p></div><div class="cards">${c('Why we exist','To develop a professionally managed mining platform in Ethiopia — one that proves responsible operations and commercial viability can grow together.')}${c('What drives us','The conviction that mining done well — with evidence, accountability and community respect — creates lasting value that extractive shortcuts never can.')}${c('How we operate','Through staged development, independent verification and a governance framework that separates ownership oversight from daily operations.')}${c('Where we stand','At a transition point: moving from founder-led operations to professional management with the right partners and technical capabilities.')}</div></section>

${photoBreak(IMG.greenMtn,'Lush green mountain landscape','THE ETHIOPIAN HIGHLANDS')}

<section class="split anim-up"><div><span class="eyebrow">OUR STORY</span><h2>Several years of ground-level work.</h2></div><div><p>Perpach was founded with a simple thesis: that an Ethiopian-based operator with genuine local knowledge could build a mining business worth investing in — if it was willing to do the hard, unglamorous work of establishing an evidence base first.</p><p>Several years of practical site work have established a real operating foundation and the lessons needed for the next phase. The early period taught us how to operate in a challenging environment, build local relationships, navigate regulatory requirements and maintain safety standards with limited infrastructure.</p><p>Today, Perpach is entering its next chapter. Ownership oversight and daily operations are being separated as professional controls, technical capacity and strategic partnerships develop. This is not a pivot — it is the plan we set out to execute.</p></div></section>

<section class="snapshot"><div class="photo-panel" style="background-image:url(${IMG.teamSA})"><span>OUR TEAM / ON THE GROUND</span></div><div><span class="eyebrow">OUR TRANSITION</span><h2>From founder-led to professionally managed.</h2><p>The next phase of Perpach requires capabilities that go beyond what any single founder can provide. We are deliberately building a leadership structure that brings in experienced mining professionals while retaining the local knowledge and relationships that make our operations possible.</p><p>This transition includes formal separation of governance and operations, introduction of independent technical oversight, and a structured approach to strategic partnership that prioritises alignment over speed.</p><dl><div><dt>GOVERNANCE</dt><dd>Separating ownership &amp; operations</dd></div><div><dt>TECHNICAL</dt><dd>Independent professional oversight</dd></div><div><dt>PARTNERSHIP</dt><dd>Aligned, patient capital</dd></div></dl><a class="button light" href="/mining/investor">Partner with us <span>↗</span></a></div></section>

<section class="section"><div class="section-head anim-up"><span class="eyebrow">OUR PRINCIPLES</span><h2>Non-negotiable standards.</h2><p>These are not aspirations. They are the operating principles we hold ourselves to today — and the basis on which we invite scrutiny.</p></div><div class="cards">${c('Evidence over narrative','We do not publish claims we cannot support. Where data is incomplete, we say so. Where work remains, we describe it honestly.')}${c('Local capability','Ethiopian talent and knowledge are not secondary inputs — they are the foundation. International expertise complements; it does not replace.')}${c('Staged commitment','We earn the right to expand by proving we can operate well at the current scale. No milestone is skipped.')}${c('Transparent reporting','Material corrections are recorded publicly. Implementation status is distinguished from future intent in all communications.')}</div></section>

<section class="pathways"><span class="eyebrow">EXPLORE FURTHER</span><h2>Learn more about our work.</h2><div><a href="/mining/projects">Our projects <span>↗</span></a><a href="/mining/responsibility">Responsibility <span>↗</span></a><a href="/mining/investor">Investor relations <span>↗</span></a><a href="/mining/contact">Get in touch <span>↗</span></a></div></section>`},

{slug:'projects',title:'Projects',description:'Explore Perpach mining projects, their current stage and development pathway.',body:`${hero('OUR PROJECTS','One foundation.<br>A focused next phase.','We present only projects where Perpach\'s role can be appropriately verified. Claims without evidence have no place here.',
'View Lunga Project','/mining/projects/lunga',IMG.quarry)}

<section class="section"><div class="section-head anim-up"><span class="eyebrow">PROJECT PORTFOLIO</span><h2>Disciplined focus.</h2><p>Our current portfolio reflects a deliberate strategy: prove the model at one site before expanding. Lunga is the foundation on which everything else will be built.</p></div><div class="cards">${imgCard('Lunga · Ethiopia','Gold · Early operation entering structured professionalisation. Current priority: establish a verified production baseline and a staged development plan backed by independent technical review.',IMG.excavator,'Lunga mining operations')}${imgCard('Pipeline assessment','Perpach evaluates potential opportunities through a structured screening process. No additional projects will be announced until Lunga\'s verification programme is substantially complete.',IMG.aerialMtn,'Ethiopian landscape')}${imgCard('Expansion criteria','New projects must meet clear thresholds for geological merit, legal clarity, community context and alignment with our staged development model.',IMG.stoneQuarry,'Quarry operations')}${imgCard('Regional focus','East Africa remains our geographic priority. We know the terrain, the regulatory environment and the communities. That knowledge is our competitive advantage.',IMG.greenMtn,'East African landscape')}</div></section>

${photoBreak(IMG.openpit,'Open pit mining operations','ACTIVE OPERATIONS / SITE LEVEL')}

<section class="split anim-up"><div><span class="eyebrow">OUR APPROACH</span><h2>How we evaluate projects.</h2></div><div><p>Every potential project goes through a structured screening process that prioritises geological merit, legal clarity, community context and alignment with our staged development model. We do not chase scale — we pursue quality.</p><p>The evaluation framework includes independent technical review, legal due diligence on all rights and permits, environmental baseline assessment, and community engagement mapping. Projects that pass initial screening enter a controlled diligence process with defined milestones.</p></div></section>

<section class="facts">${[['FLAGSHIP','Lunga, Ethiopia'],['COMMODITY','Gold'],['STAGE','Early operation'],['PATHWAY','4-stage development']].map(([s,b])=>`<div class="anim-up"><span>${s}</span><b>${b}</b></div>`).join('')}</section>

<section class="pathways"><span class="eyebrow">GO DEEPER</span><h2>Explore the Lunga Project.</h2><div><a href="/mining/projects/lunga">Lunga project profile <span>↗</span></a><a href="/mining/investor">Investor pathway <span>↗</span></a><a href="/mining/company">About Perpach <span>↗</span></a><a href="/mining/contact">General inquiry <span>↗</span></a></div></section>`},

{slug:'projects/lunga',title:'Lunga Project',description:'The canonical profile for Perpach\'s Lunga gold project in Ethiopia — geology, development pathway and partnership opportunity.',body:`${hero('LUNGA / ETHIOPIA','A practical foundation for disciplined growth.','Lunga is an early gold operation entering a structured phase of verification, operational control and professional management.',
'Partner with us','/mining/investor',IMG.truck)}

<section class="facts">${[['COMMODITY','Gold'],['STAGE','Early operation'],['FOCUS','Verify &amp; stabilise'],['MODEL','Staged development']].map(([s,b])=>`<div class="anim-up"><span>${s}</span><b>${b}</b></div>`).join('')}</section>

<section class="split anim-up"><div><span class="eyebrow">PROJECT CONTEXT</span><h2>Evidence first.</h2></div><div><p>Site work has established an early local operation. The next stage is not built on unsupported resource or return claims: it begins with independent review, controlled production records, gold accounting and clear operating responsibilities.</p><p>Legal-rights language, workforce numbers, equipment arrangements and technical results will be published only after their sources, effective dates and professional approvals are complete.</p><p>What distinguishes Lunga is not its scale — it is the discipline with which the next phase is being approached. Every decision point requires evidence. Every expansion step requires verification of the previous one.</p></div></section>

${photoBreak(IMG.truckSA,'Mining truck at quarry operations','SITE OPERATIONS / EQUIPMENT')}

<section class="dark-section"><span class="eyebrow">DEVELOPMENT PATHWAY</span><h2>Four controlled steps.</h2><ol>${[
['01 / Verify','Independent inspection, baseline data collection, geological sampling programme, and reconciliation of all historical production records. Third-party technical review of site conditions, equipment status and environmental baseline.'],
['02 / Stabilise','Implement formal safety management system, production tracking protocols, fuel and consumables reconciliation, equipment-hours logging, and chain-of-custody documentation for all gold output. Establish clear operating responsibilities.'],
['03 / Expand','Milestone-based capacity decisions supported by operating evidence. Expansion only proceeds when verification and stabilisation metrics are met. Capital deployment tied to demonstrated performance.'],
['04 / Explore','A professionally designed exploration programme targeting primary-gold potential within and adjacent to the current operation. Geological mapping, sampling and geophysical survey work guided by qualified professionals.']
].map(([b,s])=>`<li class="anim-up"><b>${b}</b><span>${s}</span></li>`).join('')}</ol></section>

<section class="snapshot"><div class="photo-panel" style="background-image:url(${IMG.goldBars})"><span>GOLD / PRIMARY COMMODITY</span></div><div><span class="eyebrow">THE OPPORTUNITY</span><h2>Why Lunga matters.</h2><p>Ethiopia's gold sector represents one of the most significant untapped opportunities in African mining. Lunga sits within a geological province that has attracted international attention but remains largely under-explored by modern standards.</p><p>What Perpach brings is not a speculative land position — it is an established operating presence, local relationships, regulatory familiarity and a founder-led commitment to building value the right way.</p><dl><div><dt>GEOLOGY</dt><dd>Prospective gold province</dd></div><div><dt>ADVANTAGE</dt><dd>Established local operation</dd></div><div><dt>APPROACH</dt><dd>Verification before expansion</dd></div></dl><a class="button light" href="/mining/investor">Investment pathway <span>↗</span></a></div></section>

<section class="risk"><h2>What remains to be established</h2><p>Mining is inherently uncertain. Material work includes confirming rights wording, technical interpretation, recovery performance, costs, environmental obligations, community context and the commercial basis for expansion.</p><p>We do not minimise these uncertainties — we organise our development pathway around resolving them systematically. Qualified partners receive controlled information through a reviewed diligence process.</p><a class="button" href="/mining/investor">Investor &amp; strategic partners <span>↗</span></a></section>`},

{slug:'responsibility',title:'Responsibility',description:'Perpach\'s approach to people, environment, communities and ethical conduct in mining operations.',body:`${hero('RESPONSIBILITY','Commitments<br>measured by action.','Our responsibility framework distinguishes what is implemented, what is being built and what is planned. We report status, not aspiration.',
'View our projects','/mining/projects',IMG.forest)}

<section class="section"><div class="section-head anim-up"><span class="eyebrow">OUR FRAMEWORK</span><h2>Honest reporting on what matters.</h2><p>We organise our responsibility commitments into four pillars. For each, we distinguish between what is currently implemented, what is under development, and what is planned for future phases.</p></div><div class="cards">${imgCard('People &amp; safety','Induction protocols, personal protective equipment standards, incident recording systems, training programmes and emergency preparedness plans. Our goal is zero harm — our reporting covers the gap between that goal and current reality.',IMG.workers,'Mining workers in safety equipment')}${imgCard('Environment','Water management, fuel storage and handling, waste segregation, land disturbance tracking and rehabilitation planning. Controls are scaled to each operational stage and upgraded as capacity grows.',IMG.forest,'Environmental conservation')}${imgCard('Communities','Consistent community engagement, local employment priority, transparent grievance mechanisms and a safe, confidential route for concerns. We work within communities, not around them.',IMG.farming,'Rural African community')}${imgCard('Ethics &amp; compliance','Anti-bribery controls, conflicts of interest management, responsible gold sales verification, evidence integrity protocols and regulatory compliance tracking. These are non-negotiable.',IMG.meeting2,'Professional business ethics')}</div></section>

${photoBreak(IMG.workers,'Workers in safety equipment at construction site','PEOPLE & SAFETY / ON SITE')}

<section class="split anim-up"><div><span class="eyebrow">IMPLEMENTATION STATUS</span><h2>Where we stand today.</h2></div><div><p>We believe the mining industry suffers from too many aspirational commitments and too few honest assessments of current practice. Perpach takes a different approach: we report what is implemented, acknowledge what is incomplete, and describe what comes next.</p><p>This means our responsibility disclosures may look less polished than those of larger companies. That is intentional. We would rather be honest about our current stage than publish commitments we cannot yet demonstrate.</p><p>As the business develops and professional management structures are established, our responsibility framework will be independently reviewed and benchmarked against recognised mining industry standards.</p></div></section>

<section class="snapshot"><div class="photo-panel" style="background-image:url(${IMG.community})"><span>COMMUNITY / LOCAL ENGAGEMENT</span></div><div><span class="eyebrow">COMMUNITY COMMITMENT</span><h2>Built on local relationships.</h2><p>Our community engagement is not a corporate programme bolted onto operations — it is woven into how we work. Local knowledge, local hiring and local accountability are foundational principles, not afterthoughts.</p><p>We maintain open communication channels with community leaders, provide regular updates on operational activities, and operate a confidential grievance mechanism accessible to all community members.</p><dl><div><dt>EMPLOYMENT</dt><dd>Local hiring priority</dd></div><div><dt>ENGAGEMENT</dt><dd>Regular community dialogue</dd></div><div><dt>GRIEVANCE</dt><dd>Confidential mechanism</dd></div></dl><a class="button light" href="/mining/contact">Contact us <span>↗</span></a></div></section>

<section class="pathways"><span class="eyebrow">RELATED</span><h2>Learn more.</h2><div><a href="/mining/company">Our company <span>↗</span></a><a href="/mining/projects/lunga">Lunga project <span>↗</span></a><a href="/mining/partnerships">Partner with us <span>↗</span></a><a href="/mining/contact">Get in touch <span>↗</span></a></div></section>`},

{slug:'partnerships',title:'Partnerships',description:'Supplier, technical, institutional and strategic partnership routes with Perpach Mining.',body:`${hero('PARTNERSHIPS','Capability that moves<br>the work forward.','We welcome serious suppliers, operating specialists, institutions and strategic mining partners. Every engagement is structured, transparent and subject to formal requirements.',
'Start a conversation','/mining/contact',IMG.handshake)}

<section class="section"><div class="section-head anim-up"><span class="eyebrow">PARTNERSHIP ROUTES</span><h2>Four ways to work with us.</h2><p>Each pathway has defined requirements, evaluation criteria and engagement protocols. We value capability and alignment over speed.</p></div><div class="cards">${imgCard('Suppliers &amp; contractors','Equipment, maintenance, logistics, safety and site services. All supplier engagements are subject to formal qualification requirements, competitive evaluation and no promise of award. We seek reliable partners who can deliver in challenging environments.',IMG.conveyor,'Mining equipment and machinery')}${imgCard('Technical partners','Geology, mine planning, mineral processing, environmental management, safety systems and financial reporting expertise. We need professionals who bring rigorous methodology and are comfortable with staged, evidence-based decision-making.',IMG.stoneQuarry,'Quarry and geological operations')}${imgCard('Institutions','Government bodies, universities, training providers, development institutions and community organisations. We welcome structured collaboration that builds local capability and supports the broader development context in which we operate.',IMG.farming,'Rural development and institutions')}${imgCard('Mining investors','Partners aligned with staged verification, professional management and long-term value creation. This is not a quick-return opportunity — it is a partnership for patient, experienced mining investors.',IMG.goldBars,'Gold investment opportunity')}</div></section>

${photoBreak(IMG.handshake,'Business partnership handshake','PARTNERSHIPS / BUILDING TOGETHER')}

<section class="split anim-up"><div><span class="eyebrow">OUR STANDARDS</span><h2>What we expect from partners.</h2></div><div><p>Perpach operates in a sector where trust is earned slowly and lost quickly. We apply the same rigour to selecting partners as we do to evaluating mining opportunities. Every potential partner goes through a structured assessment process.</p><p>We look for demonstrated capability in relevant mining or technical disciplines, alignment with our staged development approach, financial stability, and a track record of ethical business conduct. References are checked. Claims are verified.</p><p>In return, we commit to transparent communication, fair commercial terms, clear scope definitions and professional engagement throughout the relationship.</p></div></section>

<section class="form-section"><div class="anim-up"><span class="eyebrow">START A CONVERSATION</span><h2>Partnership inquiry.</h2><p>Tell us about your organisation and how you believe we can work together. All inquiries are reviewed by the appropriate team and responded to within five business days.</p><p class="fraud"><b>Important:</b> Perpach never requests fees, deposits or financial commitments as a condition of partnership discussions. Trust only correspondence from an approved @perpach.com address.</p></div>${form('partnership-inquiry')}</section>`},

{slug:'investor',title:'Investor and Strategic Partners',description:'A controlled pathway for qualified mining investors and strategic partners seeking exposure to Ethiopian gold.',body:`${hero('INVESTOR &amp; STRATEGIC PARTNERS','A real foundation.<br>A disciplined next stage.','Perpach is seeking experienced, aligned partners who understand that lasting mining value begins with verification and operating control.',
'Request the investor brief','#profile',IMG.goldBars)}

<section class="split anim-up"><div><span class="eyebrow">THE PARTNERSHIP THESIS</span><h2>Built to de-risk before scaling.</h2></div><div><p>Perpach contributes local operating experience, an established project foundation, regulatory familiarity and a founder-led commitment to transition toward professional management.</p><p>The right partner brings relevant mining capability, patient strategic capital and an evidence-led approach to verification, stabilisation, expansion and exploration.</p><p>This is not a speculative opportunity. It is a structured partnership for investors who understand that the most valuable mining assets are built through disciplined development, not promotional narratives.</p></div></section>

<section class="facts">${[['01','Verify'],['02','Stabilise'],['03','Expand'],['04','Explore']].map(([s,b])=>`<div class="anim-up"><span>STAGE ${s}</span><b>${b}</b></div>`).join('')}</section>

${photoBreak(IMG.meeting,'Strategic business partnership meeting','STRATEGIC PARTNERS / ALIGNMENT')}

<section class="snapshot"><div class="photo-panel" style="background-image:url(${IMG.goldRed})"><span>GOLD / VALUE PROPOSITION</span></div><div><span class="eyebrow">WHAT WE OFFER</span><h2>A differentiated entry point.</h2><p>Ethiopia's gold mining sector is at an early stage of professional development. Perpach offers a rare combination: established local operations, genuine community relationships, regulatory navigation experience and a willingness to submit every aspect of the business to independent professional scrutiny.</p><p>For the right partner, this represents an opportunity to participate in building a mining platform from a position of operational reality rather than greenfield speculation.</p><dl><div><dt>FOUNDATION</dt><dd>Established local operation</dd></div><div><dt>APPROACH</dt><dd>Evidence-led development</dd></div><div><dt>STRUCTURE</dt><dd>Professional governance transition</dd></div><div><dt>ALIGNMENT</dt><dd>Patient, capable capital</dd></div></dl><a class="button light" href="#profile">Submit your profile <span>↗</span></a></div></section>

<section class="dark-section"><span class="eyebrow">ENGAGEMENT PROCESS</span><h2>How partnership works.</h2><ol>${[
['01 / Initial inquiry','Submit a partnership profile through the form below. Every inquiry is reviewed manually by the Perpach team. We assess alignment, capability and strategic fit.'],
['02 / Preliminary review','Approved inquiries receive a watermarked summary brief. This document provides an overview of the opportunity without disclosing controlled technical or commercial information.'],
['03 / Controlled diligence','Qualified partners who proceed to diligence receive access to a controlled data room with technical, financial and legal information. All materials are watermarked and subject to confidentiality obligations.'],
['04 / Partnership structuring','Aligned parties enter structured commercial discussions. Terms are negotiated with professional advisors on both sides. The goal is a partnership that serves the long-term interests of all stakeholders.']
].map(([b,s])=>`<li class="anim-up"><b>${b}</b><span>${s}</span></li>`).join('')}</ol></section>

<section class="form-section" id="profile"><div class="anim-up"><span class="eyebrow">QUALIFIED ENGAGEMENT</span><h2>Submit a partnership profile.</h2><p>Every inquiry is reviewed manually. Approved recipients may receive a watermarked brief before any controlled diligence. This is not an offer to sell securities.</p><p>We are looking for partners with demonstrated mining sector experience, patient capital and alignment with our evidence-led development approach.</p></div>${form('investor-profile')}</section>`},

{slug:'newsroom',title:'Newsroom',description:'Approved, dated Perpach company, operational and responsibility updates.',body:`${hero('NEWSROOM','The official record.','Dated company, operational and responsibility updates. Material corrections are recorded transparently. This is not a marketing channel — it is an accountability mechanism.',
'Subscribe to updates','/mining/contact',IMG.aerialMtn)}

<section class="section"><div class="section-head anim-up"><span class="eyebrow">2026 UPDATES</span><h2>Latest from the field.</h2><p>All updates are dated, approved by management and subject to correction if material inaccuracies are identified after publication.</p></div><div class="cards">${imgCard('12 AUG 2026 · OPERATIONS','A stronger production-control baseline at Lunga. New measurement protocols have been implemented across all active zones, with daily reconciliation of gold output against equipment hours, fuel consumption and labour inputs. Early data suggests the controls are working — but the dataset is still young.',IMG.openpit,'Mining operations')}${imgCard('04 AUG 2026 · COMPANY','Building the right partnerships for the next phase. Perpach has begun a structured outreach to identify strategic partners with demonstrated mining capability, patient capital and alignment with our evidence-led approach. Initial conversations are underway with several qualified groups.',IMG.meeting,'Business partnership')}${imgCard('22 JUL 2026 · RESPONSIBILITY','Turning responsibility commitments into tracked implementation. An internal review of all published responsibility commitments has been completed, with each item classified as implemented, in progress or planned. The results will inform our next public responsibility update.',IMG.forest,'Environmental responsibility')}</div></section>

${photoBreak(IMG.openpit,'Active mining site with heavy equipment','OPERATIONS / PROGRESS UPDATE')}

<section class="section"><div class="section-head anim-up"><span class="eyebrow">EARLIER UPDATES</span><h2>Previous reports.</h2><p>We maintain a complete archive of all published updates. Earlier items below reflect the progression of our work.</p></div><div class="cards">${c('08 JUL 2026 · OPERATIONS','Site safety review completed. All active work areas inspected against updated safety protocols. Three improvement actions identified and scheduled for completion by end of August.')}${c('21 JUN 2026 · COMPANY','Governance framework update. Draft terms of reference for an independent advisory board have been prepared. Final structure to be confirmed following strategic partner engagement.')}${c('05 JUN 2026 · RESPONSIBILITY','Community engagement session held with local leaders. Topics covered: employment opportunities, environmental management, grievance mechanism awareness. Attendance and key discussion points recorded.')}</div></section>

<section class="split anim-up"><div><span class="eyebrow">EDITORIAL POLICY</span><h2>How we report.</h2></div><div><p>All newsroom content is reviewed and approved by Perpach management before publication. We distinguish between facts (verified, sourced) and forward-looking statements (clearly labelled, qualified).</p><p>If a material inaccuracy is identified in any published update, we will publish a dated correction in this newsroom and update the original item. We do not quietly edit past statements — corrections are transparent and permanent.</p><p>This newsroom is not a promotional channel. It exists to provide stakeholders with an accurate, dated record of Perpach's activities and decisions.</p></div></section>

<section class="pathways"><span class="eyebrow">STAY CONNECTED</span><h2>Other ways to engage.</h2><div><a href="/mining/company">About Perpach <span>↗</span></a><a href="/mining/projects/lunga">Lunga project <span>↗</span></a><a href="/mining/investor">Investor relations <span>↗</span></a><a href="/mining/contact">Contact us <span>↗</span></a></div></section>`},

{slug:'careers',title:'Careers',description:'Work at Perpach Mining — current opportunities, recruitment safety and workplace standards.',body:`${hero('CAREERS','Build where your<br>work matters.','We value local knowledge, technical curiosity, accountable leadership and the conviction to do difficult work properly. If that sounds like you, we want to hear from you.',
'Contact careers','/mining/contact',IMG.teamSA)}

<section class="section"><div class="section-head anim-up"><span class="eyebrow">WORKING AT PERPACH</span><h2>What to expect.</h2><p>We are building a mining business from the ground up. That means every person matters, every role is visible and the work is real.</p></div><div class="cards">${imgCard('Current vacancies','There are no publicly approved vacancies at present. When roles open, they will appear here with a clear job description, closing date and transparent selection process. We do not maintain rolling applications.',IMG.excavator,'Mining site operations')}${imgCard('Recruitment safety','Perpach never charges application fees, requests bank details, passports or sensitive identification at first contact, or asks candidates to transfer money. If you receive such a request claiming to be from Perpach, it is fraudulent.',IMG.workers,'Workers in safety gear')}${imgCard('Workplace standard','Safety, dignity, equal opportunity and clear accountability are expected across all Perpach workplaces. We are building a culture where problems are reported, not hidden, and where every team member returns home safely.',IMG.teamSA,'Construction team collaboration')}${imgCard('Development &amp; growth','As Perpach grows, so do the opportunities. We prioritise internal development and local talent. Our professionalisation programme includes technical training, leadership development and clear progression pathways.',IMG.meeting,'Professional development')}</div></section>

${photoBreak(IMG.workers,'Team of workers in safety equipment','OUR PEOPLE / THE FOUNDATION')}

<section class="split anim-up"><div><span class="eyebrow">OUR CULTURE</span><h2>Built on accountability.</h2></div><div><p>Perpach is not a large corporate employer — yet. We are a growing business where individual contribution is visible and valued. The culture we are building prioritises honesty over hierarchy, evidence over opinion, and safety over speed.</p><p>We look for people who are comfortable with ambiguity, willing to build systems from scratch, and motivated by the challenge of doing difficult work properly in a demanding environment. If you need polished offices and established processes, we are probably not the right fit — yet. If you want to help build them, we might be exactly right.</p></div></section>

<section class="snapshot"><div class="photo-panel" style="background-image:url(${IMG.sunset})"><span>ETHIOPIA / WHERE WE WORK</span></div><div><span class="eyebrow">LOCATION</span><h2>Ethiopia.</h2><p>Our operations are based in Ethiopia. Working here means engaging with one of Africa's most dynamic and complex business environments. It requires cultural sensitivity, adaptability and genuine respect for local communities and customs.</p><p>For the right people, it also offers an extraordinary professional opportunity: the chance to build a mining business from its foundations in one of the world's most geologically prospective regions.</p><dl><div><dt>BASE</dt><dd>Ethiopia</dd></div><div><dt>SECTOR</dt><dd>Gold mining</dd></div><div><dt>STAGE</dt><dd>Growth phase</dd></div></dl><a class="button light" href="/mining/contact">Express interest <span>↗</span></a></div></section>

<section class="pathways"><span class="eyebrow">EXPLORE</span><h2>Learn more about Perpach.</h2><div><a href="/mining/company">Our company <span>↗</span></a><a href="/mining/responsibility">Responsibility <span>↗</span></a><a href="/mining/projects">Our projects <span>↗</span></a><a href="/mining/contact">Contact us <span>↗</span></a></div></section>`},

{slug:'contact',title:'Contact',description:'Route your inquiry to the correct Perpach mining team.',body:`${hero('CONTACT','Start with the right conversation.','General company, government, community, supplier, technical and media inquiries are reviewed and routed to the appropriate team within five business days.',
'Investor inquiry','/mining/investor',IMG.meeting2)}

<section class="facts">${[['GENERAL','Company &amp; media inquiries'],['PARTNERSHIPS','Supplier &amp; technical'],['INVESTOR','Strategic capital'],['CAREERS','Employment interest']].map(([s,b])=>`<div class="anim-up"><span>${s}</span><b>${b}</b></div>`).join('')}</section>

<section class="form-section"><div class="anim-up"><span class="eyebrow">GENERAL INQUIRY</span><h2>How can we help?</h2><p>Normal response target: five business days. Careers and investor inquiries should use their dedicated pathways for faster routing.</p><p class="fraud"><b>Fraud warning:</b> Trust only correspondence from an approved @perpach.com address. Never send money in response to an unsolicited message. Perpach will never ask you for fees, deposits or financial commitments via email or messaging.</p></div>${form('general-contact')}</section>

<section class="split anim-up"><div><span class="eyebrow">ROUTING</span><h2>Dedicated pathways.</h2></div><div><p>Different inquiries require different expertise. To ensure your message reaches the right team as quickly as possible, we maintain dedicated pathways for specific inquiry types.</p><ul class="route-list"><li><b>Investor &amp; strategic partners</b> — Use the <a href="/mining/investor">investor pathway</a> for all investment-related inquiries. This ensures your profile is reviewed by the appropriate team.</li><li><b>Careers</b> — Visit our <a href="/mining/careers">careers page</a> for current vacancies and recruitment information. General employment inquiries can be submitted through this contact form.</li><li><b>Partnerships &amp; suppliers</b> — For structured partnership discussions, visit our <a href="/mining/partnerships">partnerships page</a> and submit a partnership inquiry.</li><li><b>Media</b> — Journalists and media representatives should identify themselves as such in the contact form. We aim to respond to media inquiries within 48 hours.</li></ul></div></section>

<section class="pathways"><span class="eyebrow">QUICK LINKS</span><h2>Find what you need.</h2><div><a href="/mining/investor">Investor relations <span>↗</span></a><a href="/mining/partnerships">Partnerships <span>↗</span></a><a href="/mining/careers">Careers <span>↗</span></a><a href="/mining/newsroom">Newsroom <span>↗</span></a></div></section>`},

...['privacy','terms','website-disclosures'].map(slug=>({slug,title:slug==='website-disclosures'?'Website Disclosures':slug==='privacy'?'Privacy Notice':slug==='terms'?'Website Terms':slug,description:'Perpach website legal information.',body:`${hero('LEGAL',slug==='privacy'?'Privacy notice.':slug==='terms'?'Website terms.':'Website disclosures.','This interim notice is subject to legal review. Personal information submitted through this website is used only to route and respond to the inquiry for which it was provided.','Contact us','/mining/contact')}

<section class="legal">${slug==='privacy'?`<h2>Interim privacy notice</h2>
<h3>Information we collect</h3><p>When you submit a form on this website, we collect the information you provide: your name, email address, organisation and message content. We do not use tracking cookies, analytics pixels or third-party advertising tools.</p>
<h3>How we use your information</h3><p>Personal information is used solely to route your inquiry to the appropriate Perpach team and respond to your message. We do not sell, share or transfer your information to third parties except where required by law.</p>
<h3>Data retention</h3><p>Inquiry data is retained for the period necessary to respond to and resolve your inquiry, plus a reasonable retention period for record-keeping purposes. Specific retention periods will be published after legal confirmation.</p>
<h3>Your rights</h3><p>You may request access to, correction of, or deletion of your personal information by contacting us through the general inquiry form. We will respond to such requests within a reasonable timeframe.</p>
<h3>Contact</h3><p>Questions about this privacy notice should be directed through our <a href="/mining/contact">contact page</a>.</p>
<p class="legal-note">Exact data-controller details, retention schedules, jurisdiction and applicable law will be published after legal confirmation.</p>`:

slug==='terms'?`<h2>Interim website terms</h2>
<h3>Acceptance of terms</h3><p>By accessing this website, you accept these terms of use. If you do not agree, please do not use this site.</p>
<h3>Content and accuracy</h3><p>This website provides general corporate information about Perpach. While we make reasonable efforts to ensure accuracy, all content is provided "as is" without warranty. Information may be updated without notice.</p>
<h3>Not investment advice</h3><p>Nothing on this website constitutes investment advice, a public offering, a solicitation to purchase securities, or a representation of mineral resources or reserves. Any investment-related discussions occur through controlled, documented channels with appropriate professional advice.</p>
<h3>Intellectual property</h3><p>All content, logos, design elements and materials on this website are the property of Perpach or its licensors. You may not reproduce, distribute or create derivative works without written permission.</p>
<h3>Limitation of liability</h3><p>To the maximum extent permitted by law, Perpach accepts no liability for any loss or damage arising from the use of this website or reliance on its contents.</p>
<h3>Governing law</h3><p>These terms are governed by applicable law, the specifics of which will be published after legal confirmation.</p>
<p class="legal-note">Complete terms including jurisdiction, dispute resolution and specific liability provisions will be published after legal review.</p>`:

`<h2>Website disclosures</h2>
<h3>Site operator</h3><p>This website is operated by Perpach. Exact corporate entity details, registered address and licence-holder information will be published after legal confirmation.</p>
<h3>Forward-looking statements</h3><p>This website may contain forward-looking statements about Perpach's plans, expectations and objectives. These statements are clearly identified where they appear and are subject to risks and uncertainties that could cause actual results to differ materially.</p>
<h3>No offer of securities</h3><p>Nothing on this website constitutes an offer to sell or a solicitation to purchase securities in any jurisdiction. Any such offer would be made only through appropriate legal documentation with proper regulatory compliance.</p>
<h3>Mineral resource statements</h3><p>This website does not contain mineral resource or reserve estimates as defined by any recognised reporting code (JORC, NI 43-101, SAMREC or equivalent). Any geological or production references describe operational observations, not classified resources.</p>
<h3>Professional advice</h3><p>Information on this website is general in nature and does not constitute professional advice of any kind. Readers should seek independent professional advice appropriate to their circumstances.</p>
<p class="legal-note">Complete disclosure documentation will be published after legal review and regulatory confirmation.</p>`}
</section>`}))];
